git :
  commit : '@git.commit.id.abbrev@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : kvmix-dashboard
  liquibase :
    change-log : db/changelog.xml
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    url : ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username : ${DATASOURCE_USERNAME:myuser}
    password : ${DATASOURCE_PASSWORD:secret}
    driver-class-name : ${DATASOURCE_DRIVER:org.postgresql.Driver}
    hikari :
      pool-name : Hikari
      auto-commit : false
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy : org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view : true
    properties :
      hibernate.jdbc.time_zone : UTC
      hibernate.id.new_generator_mappings : true
      hibernate.connection.provider_disables_autocommit : true
      hibernate.cache.use_second_level_cache : true
      hibernate.cache.use_query_cache : true
      hibernate.generate_statistics : false
      hibernate.jdbc.batch_size : 25
      hibernate.order_inserts : true
      hibernate.order_updates : true
      hibernate.query.fail_on_pagination_over_collection_fetch : true
      hibernate.query.in_clause_parameter_padding : true
    show-sql : false
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false

  jackson :
    default-property-inclusion : NON_NULL
    serialization :
      indent-output : true
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}
  mail:
    host: localhost
    port: 1025
    username:
    password:

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful
  forward-headers-strategy : framework
  tomcat :
    redirect-context-root : false

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  info :
    env :
      enabled : true
    java :
      enabled : true
    os :
      enabled : true
  server :
    port : ${MANAGEMENT_SERVER_PORT:8080}
    add-application-context-header : true

  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, info, env, openapi, swagger-ui
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    info :
      enabled : true
    env :
      enabled : true
      show-values : always
    prometheus :
      enabled : true

springdoc :
  show-actuator : false


kvmix:
  clientApp:
    name: 'dashboardApp'
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${kvmix.clientApp.name}-alert,X-${kvmix.clientApp.name}-error,X-${kvmix.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: MjVkMjY4N2UwMWZhOTZlN2M5ZmEzNTE5YzdkNmJiMDJhNDU0OTU2YTUyYjA2OTE5Zjc5ZDZlNGRkMDI3OWRlNjhjYzgxMTJkZGI1MWI5Y2E0NGFmNDI3MjlkMzNhODU1OGU0YWY1OTkwMGJiOWI4YWE4ZDFlMTA2ODNhM2EyMjI=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
